name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run_job:
        description: Run Specific Job
        type: boolean
        required: false
      custom_message:
        description: Enter a custom message
        required: true
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"
  
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Custom Message
        run: echo ${{ inputs.custom_message }}

      - if: ${{ inputs.run_job == true }} 
        name: Printing run-job boolean value
        run: echo ${{ inputs.run_job }}